name: CI

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:

jobs:
  mingw:
    strategy:
      fail-fast: true
      matrix:
        include: [
#          { msystem: MINGW64, project: 'mingw-gcc', bindir: 'win64_mingw-gcc' },
          { msystem: CLANG64, project: 'mingw-clang', bindir: 'win64_mingw-clang' },
        ]
    name: mingw-${{ matrix.msystem }}
    runs-on: windows-latest
    steps:
      - name: Checkout bgfx
        uses: actions/checkout@v4
        with:
          path: bgfx
      - name: Checkout bx
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bx
          path: bx
      - name: Checkout bimg
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bimg
          path: bimg
      - name: Prepare
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          update: true
          install: make
          pacboy: cc:p
      - name: Build
        shell: msys2 {0}
        run: |
          cd bgfx
          make ${{ matrix.project }}-release64 -j$(nproc) AR=ar CC=cc CXX=c++ MINGW=$MINGW_PREFIX
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: shaderc-win-x64.exe
          path: ./bgfx/.buildk/${{ matrix.bindir }}/bin/shadercRelease.exe
  linux:
    strategy:
      fail-fast: true
      matrix:
        include: [
          { config: release, binsuffix: Release },
        ]
    name: linux-${{ matrix.config }}64
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout bgfx
        uses: actions/checkout@v4
        with:
          path: bgfx
      - name: Checkout bx
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bx
          path: bx
      - name: Checkout bimg
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bimg
          path: bimg
      - name: Build
        run: |
          sudo apt install libgl-dev
          cd bgfx
          make -j$(nproc) linux-${{ matrix.config }}64
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: shaderc-linux-x64
          path: ./bgfx/.build/linux64_gcc/bin/shaderc${{ matrix.binsuffix }}
  osx:
    strategy:
      fail-fast: true
      matrix:
        include: [
          { config: release, binsuffix: Release },
        ]
    name: osx-x64-${{ matrix.config }}
    runs-on: macos-latest
    steps:
      - name: Checkout bgfx
        uses: actions/checkout@v4
        with:
          path: bgfx
      - name: Checkout bx
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bx
          path: bx
      - name: Checkout bimg
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bimg
          path: bimg
      - name: Build
        run: |
          cd bgfx
          make -j$(sysctl -n hw.physicalcpu) osx-x64-${{ matrix.config }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: shaderc-osx-x64
          path: ./bgfx/.build/osx-x64/bin/shaderc${{ matrix.binsuffix }}
  android:
    strategy:
      fail-fast: true
      matrix:
        include: [
          { platform: arm },
          { platform: arm64 },
        ]
    name: android-${{ matrix.platform }}
    runs-on: ubuntu-22.04
    steps:
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b
          add-to-path: false
      - name: Checkout bgfx
        uses: actions/checkout@v4
        with:
          path: bgfx
      - name: Checkout bx
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bx
          path: bx
      - name: Checkout bimg
        uses: actions/checkout@v4
        with:
          repository: bkaradzic/bimg
          path: bimg
      - name: Build
        run: |
          cd bgfx
          make -j$(sysctl -n hw.physicalcpu) android-${{ matrix.platform }}
        env:
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Check
        run: |
          cd bgfx
          ls -lash ".build/android-${{ matrix.platform }}/bin"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: shaderc-linux-${{ matrix.platform }}
          path: ./bgfx/.build/android-${{ matrix.platform }}/bin/shadercRelease
